### ISSUE TITLE
React Suspense stopping build

### ISSUE THREAD

**Issue by lilyx13** [containers/website-new#18]
After merge to typescript, I found that the Suspense tag is messing with the static build.

## TODO
- [ ] verify that build is fine without need to lazy load
- [ ] if not, get Suspense to work or find an alternative strategy
- [ ] if so, get the import to stop throwing warnings.

**Comment by lilyx13** [comment]
I found a couple labelling bugs when testing this problem so I'll open up a bugfix pr that addresses those as well as this.

**Comment by lilyx13** [comment]
This is closed. currently not using suspense, fixing the warning for the react-markdown import wasn't worth it to keep focusing on this at this time.

**Comment by lilyx13** [comment]
In #27 I figured out how to combine browser only with lazy loading that fixed the issues surrounding this.
